Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,9 +46,16 @@ jobs:
 
       - name: Run with bad input
         run: |
-          .\lab1.exe gkaygakydfla
-          IF ($LASTEXITCODE -eq 0) {
-          echo "Program should have failed for bad input!"
-          exit 1
+          $ErrorActionPreference = "Stop"  # Ensure any error stops the execution
+          try {
+              .\lab1.exe gkaygakydfla
+              if ($LASTEXITCODE -eq 0) {
+                  Write-Output "Program should have failed for bad input!"
+                  exit 1 # Fail the workflow.
+              }
+          } catch {
+              Write-Output "Program crashed or encountered an exception!"
+              exit 1 # Fail the workflow.
           }
+
 
